"""
Step 3 — YOLOv8 Training (CPU-optimized)

Install dependencies first:
    pip install ultralytics pyyaml

Usage:
    python step3_train.py

Output:
    runs/detect/fasteners/weights/best.pt   ← use this in inference
    runs/detect/fasteners/weights/last.pt
"""

from ultralytics import YOLO
import yaml
import os
import time

# ── Training config ────────────────────────────────────────────────────────────

MODEL       = "yolov8n.pt"    # nano — smallest and fastest; best for CPU
                               # other options (larger/more accurate):
                               # "yolov8s.pt" (small), "yolov8m.pt" (medium)

DATASET     = "dataset.yaml"   # generated by step2_prepare_dataset.py
EPOCHS      = 50               # increase to 100 if accuracy is low
IMG_SIZE    = 416              # smaller = faster on CPU; 640 is standard
BATCH_SIZE  = 4                # keep low on CPU (4–8)
WORKERS     = 2                # data loading threads; 2 is safe on CPU
PROJECT     = "runs/detect"
RUN_NAME    = "fasteners"
DEVICE      = "cpu"            # force CPU


def train():
    if not os.path.exists(DATASET):
        print(f"[ERROR] {DATASET} not found.")
        print("Run step2_prepare_dataset.py first.")
        return

    with open(DATASET) as f:
        cfg = yaml.safe_load(f)

    print("\n=== YOLOv8 TRAINING ===")
    print(f"  Model    : {MODEL}")
    print(f"  Classes  : {cfg.get('names')}")
    print(f"  Epochs   : {EPOCHS}")
    print(f"  Img size : {IMG_SIZE}")
    print(f"  Device   : {DEVICE}")
    print(f"\n  CPU training is slower — estimated time:")
    n_train = len(os.listdir(os.path.join(cfg['path'], cfg['train'])))
    est_mins = (n_train * EPOCHS * 0.15) / 60
    print(f"  ~{est_mins:.0f}–{est_mins*2:.0f} minutes for {n_train} images × {EPOCHS} epochs")
    print("  Tip: leave it running overnight if needed.\n")

    model = YOLO(MODEL)

    t0 = time.time()
    results = model.train(
        data        = DATASET,
        epochs      = EPOCHS,
        imgsz       = IMG_SIZE,
        batch       = BATCH_SIZE,
        workers     = WORKERS,
        device      = DEVICE,
        project     = PROJECT,
        name        = RUN_NAME,
        exist_ok    = True,

        # CPU-friendly augmentations
        hsv_h       = 0.015,   # hue jitter
        hsv_s       = 0.5,     # saturation jitter — helps with metallic reflections
        hsv_v       = 0.3,     # brightness jitter
        fliplr      = 0.5,     # horizontal flip
        flipud      = 0.1,     # vertical flip
        degrees     = 15,      # rotation ±15° — fasteners can sit at any angle
        scale       = 0.3,     # zoom augmentation
        mosaic      = 0.5,     # mosaic augmentation (4 images combined)
        mixup       = 0.0,     # disable mixup on CPU (expensive)

        # Early stopping — stops training if no improvement
        patience    = 15,

        # Logging
        plots       = True,    # saves confusion matrix, PR curve etc.
        verbose     = True,
    )

    elapsed = (time.time() - t0) / 60
    best_model = f"{PROJECT}/{RUN_NAME}/weights/best.pt"

    print(f"\n=== TRAINING COMPLETE ({elapsed:.1f} min) ===")
    print(f"  Best model : {best_model}")
    print(f"  mAP@50     : {results.results_dict.get('metrics/mAP50(B)', 'N/A'):.3f}")
    print(f"\nNext step: run step4_inference.py")

    # Quick validation pass on val set
    print("\nRunning validation...")
    model.val(data=DATASET, imgsz=IMG_SIZE, device=DEVICE)


if __name__ == "__main__":
    train()
